### ISSUE TITLE
JSON+LD: Error rendering JSON payload causes Google issues

### ISSUE THREAD

**Issue by gusnaughton** [AlaskaAirlines/auro-flight#99] opened 2023-10-25 18:13 UTC
### Please verify the version of auro-flight you have installed

2.4.0

### Please describe the bug

The appliaction/ld+json payload seems to not be rendering as a consistent, JSON-compliant string in the DOM.

Go to www.alaskaair.com/status/day/today/2 and control+f for "auro-flight-main":
<img width="351" alt="image" src="https://github.com/AlaskaAirlines/auro-flight/assets/7005799/cd9251cf-2278-43a5-b972-03cd0d2d47af">

```
<script type="application/ld+json">
          {
            "@context": "https://schema.org/",
            "@type": "Flight",
            "departureTime": "<!---->10/25/2023 17:25:00 PM",
            "arrivalTime": "<!---->10/25/2023 19:20:00 PM",
            "estimatedFlightDuration": "<!---->NaN",
            "name": "Flight<!----> <!---->AS 2059",
            "arrivalAirport": "<!---->SFO",
            "departureAirport": "<!---->PAE",
            "description": "Departs from <!---->PAE at <!---->5:25 PM, arrives <!---->SFO at <!---->7:20 PM"
          }
        <!----></script>
```

Google is having an issue parsing this, resulting in thousands of pages containing the following error:
```
Missing a closing brace or object member name.
```

### Reproducing the error on the docsite

No, this is an issue with Svelte's implementation of Auro

### Expected behavior

The JSON+LD payload must not have any HTML elements or comments in it.

**Comment by blackfalcon** [comment] 2023-10-31 18:12
Can you provide more data as to what the issue is you are seeing? Running this page through the Schema.org validator, it is not having any issues with there being comments in the code? https://validator.schema.org/#url=https%3A%2F%2Fwww.alaskaair.com%2Fstatus%2Fday%2Ftoday%2F2

From what I am seeing there is a 'comment' in the string value, `<!---->10/31/2023 14:00:00 PM`, but the validator doesn't appear to be having an issue with that. What is the error you are seeing?

**Comment by blackfalcon** [comment] 2023-10-31 18:15
This is an interesting thread on the error `Missing a closing brace or object member name.`

https://stackoverflow.com/questions/38053609/json-ld-missing-or-object-member-name-error

**Comment by blackfalcon** [comment] 2023-10-31 18:46
After reviewing and talking with @gusnaughton the value of this feature is in question and appears to be causing more issues than solving problems. 

The plan is to deprecate this feature from the element and look to revise this at a later time. 

## Exit Criteria 

Remove the code that supports the Schema.org SEO implementation and comment as such in the commit when and where this was removed so that it can be revised at a later time.

**Closed** 2024-01-22 00:11 UTC
Labels: auro-flight, Type: Perf
